apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg-mysql
data:
  MYSQL_ROOT_PASSWORD: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: cfg-mysql
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            value: wordpress
          - name: MYSQL_USER
            value: wordpress
          - name: MYSQL_PASSWORD
            value: wordpress
        volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
        resources:
          limits:
            memory: "500Mi"
            cpu: "250m"
        ports:
          - containerPort: 3306
      volumes:
          - name: mysql-volume
            emptyDir:
              {}
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306