apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg-mysql
data:
  MYSQL_ROOT_PASSWORD: password
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.6
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          configMapKeyRef:
            name: cfg-mysql
            key: MYSQL_ROOT_PASSWORD
    resources:
      limits:
        memory: "500Mi"
        cpu: "500m"
    ports:
      - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mysql
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
  - port: 3306
    nodePort: 30031
