apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:5.8.1
        env:
          - name: WORDPRESS_DB_HOST
            value: svc-mysql:3306
          - name: WORDPRESS_DB_USER
            value: wordpress
          - name: WORDPRESS_DB_NAME
            value: wordpress
          - name: WORDPRESS_DB_PASSWORD
            value: wordpress
        volumeMounts:
          - mountPath: /var/www/html
            name: web-data
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
          - containerPort: 80
      volumes:
        - name: web-data
          emptyDir:
            {}

---
apiVersion: v1
kind: Service
metadata:
  name: svc-wordpress
spec:
  selector:
    app: wordpress
  ports:
  - port: 8080
    targetPort: 80
